// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSKVXV7MzniTCfhXffHxy9DzEN8jf_pl4',
    appId: '1:624312826756:web:70f19f629187f3a4653bd1',
    messagingSenderId: '624312826756',
    projectId: 'crud-dac51',
    authDomain: 'crud-dac51.firebaseapp.com',
    storageBucket: 'crud-dac51.appspot.com',
    measurementId: 'G-8RN4GNBLP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcKWLiB8PB-uGZs0du8cgWair3vnSiF6g',
    appId: '1:624312826756:android:1595ce32fe6c4438653bd1',
    messagingSenderId: '624312826756',
    projectId: 'crud-dac51',
    storageBucket: 'crud-dac51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlYjPCiF5BvqeyjaoKZrWZwhCRI4qVWnc',
    appId: '1:624312826756:ios:b9bd4cdebf9b5010653bd1',
    messagingSenderId: '624312826756',
    projectId: 'crud-dac51',
    storageBucket: 'crud-dac51.appspot.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlYjPCiF5BvqeyjaoKZrWZwhCRI4qVWnc',
    appId: '1:624312826756:ios:d91e24ca4977ac56653bd1',
    messagingSenderId: '624312826756',
    projectId: 'crud-dac51',
    storageBucket: 'crud-dac51.appspot.com',
    iosBundleId: 'com.example.crudFirebase.RunnerTests',
  );
}
